### ISSUE TITLE
RWD broken

### ISSUE THREAD

**Issue by TigerHuang** [CPRTeam/CCIP-Landing#1]
Bug as image
Device: iPhone 5
![image](https://cloud.githubusercontent.com/assets/1662405/17644750/ce53b608-61c1-11e6-919e-b971bdb619e1.jpeg)

**Comment by Haraguroicha** [comment]
@TigerHuang 

iOS Version please?

and the page was opened by what app? Mail.app or ... ?

**Comment by TigerHuang** [comment]
@Haraguroicha 
iOS 8.1.2 / Facebook Messenger
